### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by DevilIris** [ETCLabs/RDMnetBroker#6]
Hello Guys!

Just wondering if with this software it is possible to integrate the Hog4 Software or the Lighting from ETH and make a plugin for Elgato Stream Deck?

**Comment by nwagner** [comment]
I don't think this is applicable for what you are asking.  You might try customer service or the Hog 4 forums https://community.etcconnect.com/control_consoles/hog-4-lighting-controls/

**Comment by minorDeveloper** [comment]
@DevilIris I'd recommend looking into [Bitfocus Companion](https://github.com/bitfocus/companion). This is an open source interface for the Elgato Streamdeck system and while it has support for lots of common protocols already (OSC, TCP, MIDI, etc), the community are keen to help add integrations for new devices.
